name: Vue.js Build & Deploy Firebase Hosting 

on: 
  push:
    branches: 
      - master

jobs:
  build:

    name: Build & Deploy

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "10"
      env:
        LANG: ja_JP.UTF-8
        TZ: Asia/Tokyo
    - run: |
        node --version
        yarn install
        yarn build

    - run: |
        yarn global add firebase-tools
        `yarn global bin`/firebase deploy --only hosting --project "${PROJECT_ID}" --token "${FIREBASE_TOKEN}"
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
